### ISSUE TITLE
Fix Quit button in Space Game example

### ISSUE THREAD

**Issue by LaraEngebretson** [AtomicGameEngine/AtomicExamples#25]
The application doesn't close on iOS.

**Comment by rsredsq** [comment]
It works fine on Desktop and Android, so probably there's an issue on the native side.

**Comment by LaraEngebretson** [comment]
Moving this issue over to the main repo. Thanks!

**Comment by LaraEngebretson** [comment]
Change visibility on the quit button for iOS deploy.
