### ISSUE TITLE
Test examples to verify some shader changes

### ISSUE THREAD

**Issue by rsredsq** [AtomicGameEngine/AtomicExamples#49]
shader changes in: https://github.com/AtomicGameEngine/AtomicGameEngine/commit/6000ea69c77dcc75491ceee8cd724787e06e5429

**Comment by JoshEngebretson** [comment]
This is solely for the examples in the example browser, and please make sure to test the example in general for functionality and not just rendering, THANKS!

**Comment by rsredsq** [comment]
Ok, I've tested all the examples, and all of them works EXCELLENT!

**Comment by JoshEngebretson** [comment]
Great, thanks :+1:
