### ISSUE TITLE
Atomic.SOUND_MUSIC referenced but non-existent?

### ISSUE THREAD

**Issue by brandonlamb** [AtomicGameEngine/AtomicExamples#70]
```
SpaceGame/Resources/Scripts/utils.js
SpaceGameMultiplayer/Resources/Scripts/utils.js
AtomicExamples/ToonTown/Resources/Components/Scene.js
```

The files above make reference to Atomic.SOUND_MUSIC, but I can't find this anywhere?

**Comment by mattbenic** [comment]
It comes from Atomic\Audio\AudioDefs.h, looks like it needs to be manually added to Script\TypeScript\AtomicWork.d.ts

**Comment by brandonlamb** [comment]
Ahhh, I just realized I was in the Content/ (mac) directory doing a search, thanks for the find I'll manually add that for now!

**Comment by JoshEngebretson** [comment]
I'll look into why the constants in AudioDefs.h aren't being picked up as part of Build 1 :  https://github.com/AtomicGameEngine/AtomicGameEngine/milestone/2
