### ISSUE TITLE
How to lock mouse pointer in the player (Windows)?

### ISSUE THREAD

**Issue by n9** [AtomicGameEngine/AtomicExamples#78]
Is it possible to lock mouse pointer in the player for Windows, so it is possible to turn around using mouse?

**Comment by benwolf** [comment]
To wrap the Cursor in the window add the line "Atomic.input.setMouseMode(Atomic.MM_WRAP);" to main.js. To hide the Cursor add the line "Atomic.input.setMouseVisible(false);" also.

You could also add a hotkey to toggle it or similar.

**Comment by JoshEngebretson** [comment]
@n9 Please use the QA system to ask questions: https://qa.atomicgameengine.com/ it will help others find answers...

@benwolf Good answer :)

Thanks!
